#!/usr/bin/env python
# encoding: utf-8
# @project : MongoDB
# @author: Zekun Zhang
# @contact: zekunzhang.1996@gmail.com
# @file: csv_to_json.py
# @time: 2019-11-04
import csv
import json
from pymongo import MongoClient

path = '/Users/zekunzhang/2019 Fall/CS527/Instacart/'
path_write = '/Users/zekunzhang/2019 Fall/CS527/Instacart/'
file_names = ['aisles', 'departments', 'orders', 'products', 'order_products']
col_names = [("aisle_id", "aisle"), ("department_id", "department"),
             ("order_id", "user_id", "order_number", "order_dow", "order_hour_of_day", "days_since_prior_order"),
             ("product_id", "product_name", "aisle_id", "department_id"),
             ("order_id", "product_id", "add_to_cart_order", "reordered")]


def csv_reader():
    for file_name, col_name in zip(file_names, col_names):
        f = open(path + file_name + '.csv', 'r', newline='')
        reader = csv.DictReader(f, fieldnames=col_name)
        print(file_name + " Read successfully")
        out = json.dumps([row for row in reader])
        print(file_name + " Parse successfully")
        json_writer(output=out, table_name=file_name)
        list = json.loads(out)
        json_uploader(list=list, table_name=file_name)


def json_writer(output, table_name):
    f = open(path_write + table_name + '.json', 'w')
    f.write(output)
    print(table_name + " Write successfully")


def json_uploader(list, table_name):
    client = MongoClient("mongodb://localhost:27017/")
    db = client['instacart']
    table = db[table_name]
    table.insert_many(list)
    print(table_name + " Upload successfully")


def main():
    csv_reader()


if __name__ == '__main__':
    main()
